name: Weekly Market Watch

on:
  workflow_dispatch:  # manual run
  schedule:
    - cron: "0 9 * * 1"  # every Monday at 09:00 UTC

jobs:
  run-weekly:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      FORCE_SUMMARY: "0"  # override in secrets or here if needed

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Weekly Summary
        run: |
          python main.py
